title: ""
description: ""

url:
baseurl: ""

permalink: /:title/
markdown: kramdown

exclude:
  - .DS_Store
  - bower_components
  - node_modules
  - Gruntfile.js
  - package.json
  - .git
  - .gitignore