title: ""
description: ""

url:
baseurl: ""

permalink: /:title/
markdown: kramdown

gems:
  - sass-globbing

exclude:
  - .DS_Store
  - node_modules
  - package.json
  - Gruntfile.js
  - .sass-cache
  - .git
  - .gitignore