title: ''
description: ''

url:
baseurl: ''

permalink: /:title/
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .DS_Store
  - bower_components
  - node_modules
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - package.json
  - README.md
  - .eslintignore
  - .eslintrc.js
  - .git
  - .gitignore
  - .stylelintrc